before_cache:
- cp /tmp/classpathFile $HOME/CACHE/classpathFile
before_install:
- if [ "$TRAVIS_OS_NAME" == "osx" ];        then sed -i '' 's/<gib.enabled>true/<gib.enabled>false/'
  $TRAVIS_BUILD_DIR/pom.xml;        else sed -i 's/<gib.enabled>true/<gib.enabled>false/'
  $TRAVIS_BUILD_DIR/pom.xml;        fi
- cat /etc/mavenrc
- sudo rm /etc/mavenrc
- export MAVEN_OPTS="-Dmaven.repo.local=$HOME/.m2/repository -Xmx2g -Dorg.slf4j.simpleLogger.showDateTime=true
  -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss:SSS"
before_script:
- if [ "$TRAVIS_OS_NAME" == "osx" ];    then sed -i '' 's/<gib.enabled>false/<gib.enabled>true/'
  $TRAVIS_BUILD_DIR/pom.xml;    else sed -i 's/<gib.enabled>false/<gib.enabled>true/'
  $TRAVIS_BUILD_DIR/pom.xml;    fi
- if [[ -e $HOME/CACHE/classpathFile ]]; then cp $HOME/CACHE/classpathFile /tmp/;
  fi
jdk:
- oraclejdk8
language: java
script:
- touch /tmp/NOW
- echo GIBSTUDYSTART $(date)
- mvn test -B
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- echo TESTNUM $(find . -name TEST-*.xml -newer /tmp/NOW | wc -l)
